theme = "everforest_dark"

[editor]
#true-color is needed for both wsl and tmux to display proper theme colors
true-color = true 
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
# show hidden files
hidden = false

[keys.normal]
#allows esc to cancel highlighted text
esc = ["collapse_selection", "keep_primary_selection"]
