theme = "everforest_dark"

[editor]
#true-color is needed for both wsl and tmux to display proper theme colors
true-color = true 
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
# show hidden files
hidden = false

[keys.normal]
# allows esc to cancel highlighted text
esc = ["collapse_selection", "keep_primary_selection"]

# This is to open lazygit or other git cli apps in a new buffer inside helix for the project you're currently in
# need to remap zellij's C-g to C-l for this to work well
# [keys.normal]
# C-g = [":new", ":insert-output lazygit", ":bugger-close!", ":redraw"]
