[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.elm-language-server]
command = "elm-language-server"

[[language]]
name = "elm"
scope = "source.elm"
file-types = ["elm"]
roots = ["elm.json"]
auto-format = true
language-servers = ["elm-language-server"]
formatter = { command = "elm-format", args = ["--stdin"] }
